### ISSUE TITLE
Table row position

### ISSUE THREAD

**Issue by thehenster** [jnicklas/capybara_table#8]
I often find I need to assert the order/position of table rows. Maybe a table of resources is ordered by the time they were created, or alphabetically etc.

Got any neat suggestions using the capybara_table matchers?

If it's not possible and sounds useful, how about something like:

```
expect(find(:table, "People")).to have_table_row("First Name" => "Jonas", "Last Name" => "Nicklas", index: 1)
```

It looks like the fields and options are being separated based on whether the hash keys are strings or not, so the above would always avoid collisions between a field name of "index" and the `index` argument. https://github.com/jnicklas/capybara_table/blob/master/lib/capybara_table/rspec.rb#L12

If using the string/symbol difference is too loose then maybe a more explicit `have_table_row(fields: {}, index: 1)` while still supporting the original syntax would be possible.

I'd be happy to have a go.

**Comment by jnicklas** [comment]
Just happened to see this just now, and err, sorry for a very late response. I don't really actively work on OSS anymore, these days, but I have some fondness for this project, so I might look into it.

It shouldn't be terribly difficult to add, modifying the XPath to add an index is simple enough. And then we just need to add an expression filter to the selector.

**Comment by thehenster** [comment]
I was giving this a shot and was reading some of the capybara source code. It looks as though a major chunk of this gem's functionailty is in capybara itself now.

Spec: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/spec/session/has_table_spec.rb#L113
Implementation: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector/definition/table_row.rb

Doesn't look like it has colspan support.. Not a big loss for me personally. And doesn't have that lovely terminal-table output either :)

I'm wondering if capybara's `with_rows` expression filter will serve my needs. Taking the example I posted originally. I want to assert that some fields are in a particular row, but I don't really care about the fields in the other rows..

```
expect(page).to have_table('Table', with_rows: [
  {"First Name" => "Jonas", "Last Name" => "Nicklas"},
  {},
  {}
])
```

Either way it looks like capybara is the place to a make change if any change is worth making.. so I'll close this. Thanks.

**Comment by jnicklas** [comment]
Okay, great! Neat that some of this functionality is in Capybara now ☺️
